package exception;

public class Ex04 {

	public static void main(String[] args) {
		
		try {
			System.out.println(1/0);
			System.out.println("예외발생시 실행안됨");
		}
		catch(Exception ae){
			ae.printStackTrace();
			System.out.println("메세지 : " + ae.getMessage());
		}

	}

}
